### ISSUE TITLE
downloading 一直在显示，new 不到新工程

### ISSUE THREAD

**Issue by jessjava** [Akiq2016/wxapp-cli#1]
安装全局包，初始化后 downloading 一直在显示，new 不到新工程

**Comment by Akiq2016** [comment]
可以截图看看吗

**Comment by Akiq2016** [comment]
![image](https://user-images.githubusercontent.com/17002181/48463484-1fc9a280-e817-11e8-809b-b0fe74d53099.png)

我从新安装了一下 目前我可以正常的拉取项目和正常安装依赖，不知道你那边是怎么显示的～
另外，目前new的script style选项暂时是没有支持好的 我还没写完（这个月比较忙
然后之后是支持custom自己的项目模板的 目前我是直接拉了一个quickstart的模板 会有各种小问题。。

暂时用的比较舒服的是wxa gen而已～

**Comment by Akiq2016** [comment]
![image](https://user-images.githubusercontent.com/17002181/48463664-cf9f1000-e817-11e8-97da-c608fc376bad.png)
我从新安装了一下 目前我可以正常的拉取项目和正常安装依赖，不知道你那边是怎么显示的～
另外，目前new的script style选项暂时是没有支持好的 我还没写完（这个月比较忙
然后之后是支持custom自己的项目模板的 目前我是直接拉了一个quickstart的模板 会有各种小问题。。

暂时用的比较舒服的是wxa gen而已～

**Comment by jessjava** [comment]
⠸ Downloading...The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.


应该是 github 的 PSAkey 限制了吧？

**Comment by Akiq2016** [comment]
噢～ 那就是拉取模板那一步坏掉的 我这周有空解决一下

**Comment by jessjava** [comment]
感谢第一时间回复

之前一直关注 `mini-programm-template` 这个项目的发展，觉得很实用，后来看到说不维护了，建议使用`Cap32/wxapp-webpack-plugin` 的 webpack 版本；

现在这个wxapp-cli是两者的综合体吗

**Comment by Akiq2016** [comment]
你可以理解为 mini-programm-template 是gulp版本，cap32 开发的是 webpack 版本。

你感觉哪个好用就用哪个就行了～ 我只不过是想现在更多的都是使用webpack， 那么小程序原生开发的话 也应该尝试用一下webpack，说不维护主要是暂时精力不足，目前更想做cli这边的开发。如果后续这边完善了，也会考虑更新gulp版本，毕竟gulp版其实挺简单好用的～

暂时wxapp-cli的定位是诸如vue-cli ng-cli此类，wxa new快速生成项目（拉取默认模版），而后续是支持用户自定义要被拉取的模板，然后支持通过wxa gen 来生成page / subPackage / component，毕竟原生小程序新建页面都是新建多个，所以这里参考了angular cli，帮忙新建页面 并更新app.json等。

github.com/cantonjs 的组织下面有wxapp-boilerplate，create-wxapp-page 算是想做一个这两个东西合体的cli吧～他们的项目也很棒，但是一个是模板的配置不能自定义化，且支持的第三方库有部分相对老旧，以及那个插件也是webpack3的，我是想弄个新的。

大概就是以上这些想法～
