### ISSUE TITLE
请问一下现在模板是从哪里加载的

### ISSUE THREAD

**Issue by jessjava** [Akiq2016/wxapp-cli#2]
现在默认的好像是ts模板吧？
js能不能帮忙看一下。我自己替换了一下，webpack设置好像有点问题

**Comment by Akiq2016** [comment]
你目前拉去的模版是默认的那个吗？

**Comment by Akiq2016** [comment]
如果你要的是js + scss的话 可以拉取`cantonjs`的模板～ `wxa new projectname cantonjs/wxapp-boilerplate`。直接`wxa new projectname`的话 目前拉取的是 `feiwuteam/quickstart-miniprogram`

目前new 命令还没有很好的根据用户输入类型去生成webpack服务 直接拉的死模板，gen是相对完善能用的

**Comment by jessjava** [comment]
好的，我研究一下。
