### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by jessjava** [Akiq2016/wxapp-cli#3]
这个mini-programm-template仓库里使用es7的async/await 时需要在每个页面引用promise和regenerator

后来看了cantonjs/wxapp-boilerplate的工程说是内置了promise模块，他说的这个内置的意思是不是使用babel哪个npm包最后在webpack打包的时候打到common.js里面啦？

这里我想确认一下具体的细节，怕有兼容问题

**Comment by Akiq2016** [comment]
抱歉～看到邮件没能及时回，然后就忘记了～
使用的es6-promise 和 regenerator最后是打包进common的 可以放心使用

**Comment by jessjava** [comment]
thanks
