### ISSUE TITLE
想学习一下，在本地如何开发？

### ISSUE THREAD

**Issue by jessjava** [Akiq2016/wxapp-cli#4]
想学习一下，在本地如何开发？

**Comment by jessjava** [comment]
方便加个联系方式不

**Comment by Akiq2016** [comment]
![image](https://user-images.githubusercontent.com/17002181/49856475-d460df00-fe2a-11e8-9d45-9bb417d638e2.png)

**Comment by jessjava** [comment]
哈哈 。没事，就是想多一些交流；
